name: PHP tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.1']

    name: PHP ${{ matrix.php-versions }} tests

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, intl
        ini-values: post_max_size=256M, short_open_tag=On
        tools: php-cs-fixer, phpunit

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Execute PHPUnit tests
      run: vendor/bin/phpunit --configuration phpunit.xml
